// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: occupancy.proto

package grpc.smbuilding.occupancy;

public interface OccupancyManyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:occupancy.OccupancyManyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
