// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: occupancy.proto

package grpc.smbuilding.occupancy;

public interface OccupancyManyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:occupancy.OccupancyManyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 room = 1;</code>
   */
  int getRoom();
}
