// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperature.proto

package grpc.smbuilding.temperature;

public interface CheckTemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperature.CheckTemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float average = 1;</code>
   */
  float getAverage();
}
