// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperature.proto

package grpc.smbuilding.temperature;

public interface CheckTemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperature.CheckTemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 room = 1;</code>
   */
  int getRoom();
}
