// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperature.proto

package grpc.smbuilding.temperature;

public interface TemperatureReportRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperature.TemperatureReportRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val = 1;</code>
   */
  java.lang.String getVal();
  /**
   * <code>string val = 1;</code>
   */
  com.google.protobuf.ByteString
      getValBytes();
}
