// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperature.proto

package grpc.smbuilding.temperature;

public final class TemperatureServiceImpl {
  private TemperatureServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_temperature_CheckTemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_temperature_CheckTemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_temperature_CheckTemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_temperature_CheckTemperatureResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_temperature_TemperatureReportRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_temperature_TemperatureReportRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_temperature_TemperatureReportResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_temperature_TemperatureReportResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021temperature.proto\022\013temperature\"\'\n\027Chec" +
      "kTemperatureRequest\022\014\n\004room\030\001 \001(\005\"+\n\030Che" +
      "ckTemperatureResponse\022\017\n\007average\030\001 \001(\002\"\'" +
      "\n\030TemperatureReportRequest\022\013\n\003val\030\001 \001(\t\"" +
      "+\n\031TemperatureReportResponse\022\016\n\006result\030\001" +
      " \001(\t2\341\001\n\022TemperatureService\022c\n\020CheckTemp" +
      "erature\022$.temperature.CheckTemperatureRe" +
      "quest\032%.temperature.CheckTemperatureResp" +
      "onse\"\000(\001\022f\n\021TemperatureReport\022%.temperat" +
      "ure.TemperatureReportRequest\032&.temperatu" +
      "re.TemperatureReportResponse\"\0000\001B7\n\033grpc" +
      ".smbuilding.temperatureB\026TemperatureServ" +
      "iceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_temperature_CheckTemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_temperature_CheckTemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_temperature_CheckTemperatureRequest_descriptor,
        new java.lang.String[] { "Room", });
    internal_static_temperature_CheckTemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_temperature_CheckTemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_temperature_CheckTemperatureResponse_descriptor,
        new java.lang.String[] { "Average", });
    internal_static_temperature_TemperatureReportRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_temperature_TemperatureReportRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_temperature_TemperatureReportRequest_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_temperature_TemperatureReportResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_temperature_TemperatureReportResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_temperature_TemperatureReportResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
