// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

package grpc.smbuilding.booking;

public interface BookingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:booking.BookingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
