// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

package grpc.smbuilding.booking;

public interface BookingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:booking.BookingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numRoom = 1;</code>
   */
  int getNumRoom();
}
