// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

package grpc.smbuilding.booking;

public final class BookingServiceImpl {
  private BookingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_booking_BookingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_booking_BookingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_booking_BookingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_booking_BookingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rbooking.proto\022\007booking\"!\n\016BookingReque" +
      "st\022\017\n\007numRoom\030\001 \001(\005\"!\n\017BookingResponse\022\016" +
      "\n\006result\030\001 \001(\t2N\n\016BookingService\022<\n\007Book" +
      "ing\022\027.booking.BookingRequest\032\030.booking.B" +
      "ookingResponseB/\n\027grpc.smbuilding.bookin" +
      "gB\022BookingServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_booking_BookingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_booking_BookingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_booking_BookingRequest_descriptor,
        new java.lang.String[] { "NumRoom", });
    internal_static_booking_BookingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_booking_BookingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_booking_BookingResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
